version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: match-app:latest
    container_name: match_app_container
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/match_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Takis1234
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db
    networks:
      - app_network


  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Takis1234
      - POSTGRES_DB=match_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
